## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos_Matemática'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos_Português'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_Geografia'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_Inglês'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_História'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_Física'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_Química'])

In [3]:

tabela_acertos = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)

tabela_acertos

,Qt_acertos_Matemática,Qt_acertos_Português,Qt_acertos_Geografia,Qt_acertos_Inglês,Qt_acertos_História,Qt_acertos_Física,Qt_acertos_Química
0,6,7,7,3,1,8,3
1,19,10,0,0,0,11,8
2,14,16,0,5,7,4,4
3,10,7,3,4,0,0,8
4,7,2,2,7,0,9,3
...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3
96,8,1,4,6,1,4,3
97,23,5,0,2,4,1,5
98,0,10,3,1,5,10,11
99,11,15,0,1,6,7,2

In [4]:
# 1) Seu código aqui
pc_mat = df_mat / 24
pc_por = df_por / 18
pc_geo = df_geo /  8
pc_ing = df_ing /  8
pc_his = df_his /  8
pc_fis = df_fis /  8
pc_qui = df_qui /  8
tabela_porcentagem = round(pd.concat([pc_mat, pc_por, pc_geo, pc_ing, pc_his, pc_fis, pc_qui], axis=1),3)
tabela_porcentagem.columns = ['%_acertos_Matemática', '%_acertos_Português', '%_acertos_Geografia',
                              '%_acertos_Inglês', '%_acertos_História', '%_acertos_Física', '%_acertos_Química']
tabela_porcentagem

,%_acertos_Matemática,%_acertos_Português,%_acertos_Geografia,%_acertos_Inglês,%_acertos_História,%_acertos_Física,%_acertos_Química
0,0.250,0.389,0.875,0.375,0.125,1.000,0.375
1,0.792,0.556,0.000,0.000,0.000,1.375,1.000
2,0.583,0.889,0.000,0.625,0.875,0.500,0.500
3,0.417,0.389,0.375,0.500,0.000,0.000,1.000
4,0.292,0.111,0.250,0.875,0.000,1.125,0.375
...,...,...,...,...,...,...,...
95,0.250,0.222,0.875,0.125,0.500,1.125,0.375
96,0.333,0.056,0.500,0.750,0.125,0.500,0.375
97,0.958,0.278,0.000,0.250,0.500,0.125,0.625
98,0.000,0.556,0.375,0.125,0.625,1.250,1.375
99,0.458,0.833,0.000,0.125,0.750,0.875,0.250

In [5]:
# 2) Seu código aqui

tabela_acertos['Total_acertos'] = tabela_acertos.iloc[:, 0:].sum(axis=1)

df_total_acertos = tabela_acertos[['Total_acertos']]

df_total_acertos

    Total_acertos
0              35
1              48
2              50
3              32
4              30
..            ...
95             34
96             27
97             40
98             40
99             42

[100 rows x 1 columns]

In [32]:
# 3) Seu código aqui

Qt_questoes = 90

porcentagem_acertos['% Acertos'] = round(df_total_acertos / Qt_questoes * 100, 3)

porcentagem_acertos

    % Acertos
0      38.889
1      53.333
2      55.556
3      35.556
4      33.333
..        ...
95     37.778
96     30.000
97     44.444
98     44.444
99     46.667

[100 rows x 1 columns]

In [26]:
# 4) Seu código aqui
alunos_aprovados = df_total_acertos[df_total_acertos['Total_acertos'] > 45]

num_alunos_aprovados = len(alunos_aprovados)

print(f"Número de alunos com nota maior que 45: {num_alunos_aprovados}")

Número de alunos com nota maior que 45: 31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [8]:
# 1 e 2) seu código aqui
alunos_desqualificados = tabela_acertos[(df_mat['Qt_acertos_Matemática'] == 0) | 
                                   (df_fis['Qt_acertos_Física'] == 0) | 
                                   (df_qui['Qt_acertos_Química'] == 0)]

print("Alunos desqualificados:")


num_desqualificados = len(alunos_desqualificados)
print(f"Número de alunos desqualificados: {num_desqualificados}")
alunos_desqualificados

Alunos desqualificados:
Número de alunos desqualificados: 23

,Qt_acertos_Matemática,Qt_acertos_Português,Qt_acertos_Geografia,Qt_acertos_Inglês,Qt_acertos_História,Qt_acertos_Física,Qt_acertos_Química,Total_acertos
3,10,7,3,4,0,0,8,32
6,6,0,7,7,5,0,4,29
10,10,8,3,2,1,7,0,31
12,20,8,3,7,1,0,3,42
14,7,11,1,7,1,4,0,31
20,23,11,6,5,6,2,0,53
25,0,4,7,4,0,4,8,27
26,11,14,6,2,7,0,0,40
27,21,13,1,5,7,3,0,50
33,14,8,0,5,6,6,0,39
35,11,14,6,3,3,0,11,48
49,8,1,1,0,1,0,8,19
56,7,6,7,5,6,0,8,39
65,1,8,2,4,3,0,6,24
66,5,4,3,6,3,0,10,31
72,11,16,3,4,7,0,9,50
73,1,16,2,4,3,0,11,37
74,9,11,0,7,5,7,0,39
84,15,1,0,5,1,0,4,26
89,23,11,7,7,6,9,0,63
92,14,10,1,6,1,8,0,40
94,0,5,2,6,1,3,8,25
98,0,10,3,1,5,10,11,40

In [9]:
# 3) seu código aqui
media_hist_geog_desqualificados = round(alunos_desqualificados[['Qt_acertos_História', 'Qt_acertos_Geografia']].mean(), 3)

media_hist_geog_desqualificados.rename(index={'Qt_acertos_História': 'Média_acertos_História', 
                                               'Qt_acertos_Geografia': 'Média_acertos_Geografia'}, inplace=True)

print("Média de acertos em História e Geografia dos alunos desqualificados:")
media_hist_geog_desqualificados

Média de acertos em História e Geografia dos alunos desqualificados:

Média_acertos_História     3.435
Média_acertos_Geografia    3.217
dtype: float64

In [10]:
# 4) seu código aqui
alunos_segunda_fase = alunos_aprovados[~alunos_aprovados.index.isin(alunos_desqualificados.index)]

alunos_segunda_fase

    Total_acertos
1              48
2              50
5              50
7              49
8              58
17             52
18             50
24             50
31             54
36             56
37             52
39             49
40             47
42             48
45             48
48             55
60             48
62             46
67             46
70             62
71             53
77             53
78             66
81             55
88             50
93             56

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [11]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00004-e01ebac8-e78d-4f97-8cd7-8db01ad17b6b.c000.csv'

In [12]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';', na_values=('na', 'NaN', ' '))

In [13]:
df.head(n=10)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,40f6e830-445b-42df-b549-013091ba0639-i0b0,fcd28bb3ab3bb196f20d411b6d6c6acf5a90041e654f62...,18,2002-10-14,F,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-03,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,75c9a5f8-f1e5-4c6c-9671-36f1aa57a85f-i0b0,f0778159d57b36a0716859668b3bf60a4b98a1ce286b9e...,50,1972-07-02,M,99,SEM INFORMACAO,120030.0,10.0,FEIJO,...,2.0,Faixa Etária,FP8073,PFIZER,28290,2022-07-04,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,a93d9149-696e-45c4-b2de-f63828e17f7c-i0b0,6b2097315657a39ddeb2aa3524dcb9d4e0b8bb89adbe69...,18,2004-05-13,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,NaN,NaN,210520,SINOVAC/BUTANTAN,29501,2022-07-19,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
3,75e45828-baca-4be9-a6c1-cc6097929deb-i0b0,6ef19e8aab2f8debcc398e9a053f5cd4af87e9da6453fc...,39,1982-04-19,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,215VCD116W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-22,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,6a1dcb69-2213-4969-9684-d1baf5d04eab-i0b0,a444df4ecd8a5d0cb12bf7d9976385b79bab30bd60b34e...,8,2014-08-06,F,3,PARDA,120042.0,10.0,RODRIGUES ALVES,...,2.0,Faixa Etária,220301,SINOVAC/BUTANTAN,152,2023-03-13,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
5,75ea2992-e5d5-44f4-91e7-c45491976fea-i0b0,ba0d8ba2f8656e60d7de406ef7cd5775fa82f6d1dc1616...,21,2000-11-19,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FP7498,PFIZER,28290,2022-07-28,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
6,245e5c0b-a40d-4362-b05b-e897e23a4a45-i0b0,14edaf515628f18ca46ab17979c25e9eff1b927f7f5195...,19,2002-04-07,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-11-20,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
7,75f04f89-4215-4bdc-87a3-1c28930ea8bf-i0b0,ec03ab993804d599c7252b82b4a7888c973fe212040dbb...,85,1935-07-11,M,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,210038,SINOVAC/BUTANTAN,Organization/61189445000156,2021-03-22,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
8,26c528db-6a60-4629-9f1d-c13e1813d11a-i0b0,54aea95c591c697c6dee27d81aa954c77631599fc18753...,43,1980-01-31,M,4,AMARELA,120035.0,10.0,MARECHAL THAUMATURGO,...,2.0,Faixa Etária,230165,BUTANTAN,152,2023-12-04,Única,33,INF3,Novo PNI
9,769dcc8e-d298-4c55-ba1b-402333a3c7ca-i0b0,8552560e5f1a13ae9cdc53e08b69d8ba9eadee47cec179...,39,1983-08-02,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,GJ5106,PFIZER,28290,2023-05-18,Reforço,103,COVID-19 PFIZER - COMIRNATY BIVALENTE,Novo PNI

In [14]:
num_vacinas = df['vacina_nome'].nunique()

print(f"Número de vacinas registradas na base de dados: {num_vacinas}")

Número de vacinas registradas na base de dados: 12

In [15]:
# 2)
num_pacientes_vacinados = df['paciente_id'].nunique()

print(f"Número de pacientes vacinados: {num_pacientes_vacinados}")

Número de pacientes vacinados: 314525

In [16]:
#3)
primeira_dose = df['vacina_descricao_dose'].unique()[0]

pacientes_primeira_dose = df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()

print(f"Número de pacientes únicos que tomaram a primeira dose: {pacientes_primeira_dose}")

Número de pacientes únicos que tomaram a primeira dose: 142291

In [17]:
# 3) solução alternativa
primeira_dose = df[df['vacina_descricao_dose'] == '1ª Dose']

pacientes_primeira_dose = primeira_dose['paciente_id'].nunique()

print(f"Número de pacientes únicos que tomaram a primeira dose: {pacientes_primeira_dose}")

Número de pacientes únicos que tomaram a primeira dose: 142291

In [18]:
# 4)
pacientes_menos_18 = df[df['paciente_idade'] < 18]['paciente_id'].nunique()

print(f"Número de pacientes com menos de 18 anos vacinados: {pacientes_menos_18}")

Número de pacientes com menos de 18 anos vacinados: 67131

In [19]:
# 5)
num_estabelecimentos = df['estabelecimento_razaoSocial'].nunique()

print(f"Número de estabelecimentos que aplicaram vacinas: {num_estabelecimentos}")

Número de estabelecimentos que aplicaram vacinas: 59

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [20]:
# 1)
df_menores_18 = df[df['paciente_idade'] < 18].copy()

df_menores_18.head(n=5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
4,6a1dcb69-2213-4969-9684-d1baf5d04eab-i0b0,a444df4ecd8a5d0cb12bf7d9976385b79bab30bd60b34e...,8,2014-08-06,F,3,PARDA,120042.0,10.0,RODRIGUES ALVES,...,2.0,Faixa Etária,220301,SINOVAC/BUTANTAN,152,2023-03-13,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
13,76a5f261-ba6c-4eff-aa66-f8926a996019-i0b0,f1acba414054230059c81f66f6b0816b5f3ca9826f6acf...,13,2008-09-10,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FP8073,PFIZER,Organization/28290,2022-03-14,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
18,92074b32-5213-4684-b168-b98be3b6ad3d-i0b0,a40a6035d22d03e8118bbf38d28e0a07be133ef18fbcb2...,14,2007-06-21,F,3,PARDA,120080.0,10.0,PORTO ACRE,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-26,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
34,6c066927-0548-470f-84e2-0205eef8f24a-i0b0,62bb99714d63bfa6193eae8b639fab251956e34243a176...,17,2004-12-29,F,5,INDIGENA,120030.0,10.0,FEIJO,...,7.0,Povos Indígenas,31065BD,PFIZER,Organization/28290,2022-01-18,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
52,a6dbc79b-9d9e-48d8-8981-08dd74862b4f-i0b0,a9413c600ddde8cc9e5e437107c75514d074ebe0e73546...,16,2005-03-15,F,99,SEM INFORMACAO,110020.0,10.0,PORTO VELHO,...,2.0,Faixa Etária,FL1939,PFIZER,Organization/28290,2022-02-04,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [21]:
# 2)
df_menores_18.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [22]:
# 3)
contagem_categoria = df_menores_18['vacina_categoria_nome'].value_counts()
print(contagem_categoria)

vacina_categoria_nome
Faixa Etária                                       46633
Povos Indígenas                                     4420
Outros                                              3736
Povos e Comunidades Tradicionais                     879
Trabalhadores de Saúde                               238
População Privada de Liberdade                        64
Comorbidades                                          48
Gestantes                                             46
Pessoas com Deficiência                                6
Pessoas Institucionalizadas                            3
Trabalhadores Industriais                              2
Trabalhadores da Educação                              2
Puérperas                                              1
Funcionário do Sistema de Privação de Liberdade        1
Name: count, dtype: int64

In [23]:
# 4)
# List of columns related to the establishment
lista_variaveis_estabelecimento = ['estabelecimento_valor',
                                   'estabelecimento_razaoSocial',
                                   'estalecimento_noFantasia',
                                   'estabelecimento_municipio_codigo',
                                   'estabelecimento_municipio_nome',
                                   'estabelecimento_uf']

# Create a DataFrame with these columns
df_estabelecimento = df_menores_18[lista_variaveis_estabelecimento]
df_estabelecimento

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
4,2000016,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,UNIDADE BASICA PADRE TEODORO ARNDS,120042,RODRIGUES ALVES,AC
13,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
18,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
34,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
52,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
384599,2002299,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE ADALTO JOSE BATISTA,120020,CRUZEIRO DO SUL,AC
384600,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
384620,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS ESTEPHAN BARBARY,120039,PORTO WALTER,AC
384622,2002299,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE ADALTO JOSE BATISTA,120020,CRUZEIRO DO SUL,AC
384625,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS ESTEPHAN BARBARY,120039,PORTO WALTER,AC

In [24]:
# 5)
df_menores_18_estabelecimento = df_menores_18.loc[:, lista_variaveis_estabelecimento]
df_menores_18_estabelecimento

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
4,2000016,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,UNIDADE BASICA PADRE TEODORO ARNDS,120042,RODRIGUES ALVES,AC
13,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
18,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
34,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
52,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
384599,2002299,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE ADALTO JOSE BATISTA,120020,CRUZEIRO DO SUL,AC
384600,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
384620,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS ESTEPHAN BARBARY,120039,PORTO WALTER,AC
384622,2002299,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE ADALTO JOSE BATISTA,120020,CRUZEIRO DO SUL,AC
384625,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS ESTEPHAN BARBARY,120039,PORTO WALTER,AC

In [139]:
#6)
df_menor_lista = df_menores_18_estabelecimento.drop_duplicates()
df_menor_lista.shape

(205, 6)